---
- hosts: nodes
  become: true
  vars:
    user_names:
      - wacevedo
      - devops
  tasks:
    - name: Remove users
      user:
        name: "{{ item }}"
        state: absent
        remove: true
      loop: "{{ user_names }}"
