---
# This playbook is used to install tools and packages I use in development

- name: Set up workstation
  hosts: nodes
  vars:
    the_user: "ansible"
  tasks:
    - name: Install base packages
      ansible.builtin.include_tasks:
        file: 'tasks/basepackages.yml'

    - name: Change default shell
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: "Create code/repos directory"
      ansible.builtin.file:
        path: /home/{{ the_user }}/code/repos
        state: directory
        mode: 0755

    # TODO: the first task freezes or throws an error
    - name: 'Install oh-my-zsh'
      ansible.builtin.include_tasks:
        file: 'tasks/ohmyzsh.yml'

    - name: 'Install oh-my-tmux'
      ansible.builtin.include_tasks:
        file: 'tasks/ohmytmux.yml'

    - name: 'Install .aliases and .zsh_functions'
      ansible.builtin.include_tasks:
        file: 'tasks/addfiles.yml'

    - name: 'Install rbenv'
      ansible.builtin.include_tasks:
        file: 'tasks/rbenv.yml'

    - name: 'Install nvm'
      ansible.builtin.include_tasks:
        file: 'tasks/nvm.yml'

    - name: Add lne to .zshrc enable vi navigation in zsh
      ansible.builtin.lineinfile:
        path: /home/{{ the_user }}/.zshrc
        line: "bindkey -v"
        create: yes

    - name: Install Neovim
      ansible.builtin.include_tasks:
        file: 'tasks/neovim.yml'
