---
- name: Add lne to .zshrc to source aliases
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.zshrc
    line: '[[ -f "/home/{{ user }}/.aliases" ]] && source "/home/{{ user }}/.aliases"'
    create: yes

- name: Add line to .zshrc to source zsh functions
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.zshrc
    line: '[[ -f "/home/{{ user }}/.zsh_functions" ]] && source "/home/{{ user }}/.zsh_functions"'
    create: yes

- name: Copy aliases file
  ansible.builtin.copy:
    src: 'files/aliases'
    dest: /home/{{ user }}/.aliases
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0744

- name: Copy zsh_functions file
  ansible.builtin.copy:
    src: 'files/zsh_functions'
    dest: /home/{{ user }}/.zsh_functions
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0744

- name: Copy basic vimrc file
  ansible.builtin.copy:
    src: 'files/remote_vimrc'
    dest: /home/{{ user }}/.vimrc
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
