---
- name: Install pip tools
  ansible.builtin.pip:
    name:
      - tldr
      - yt-dlp
    extra_args: --user

- name: 'Modify .zshrc file to add support for tools installed by pip'
  ansible.builtin.lineinfile:
    path: /home/{{ the_user }}/.zshrc
    regex: '^# export PATH='
    line: 'export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH'
    owner: '{{ the_user }}'
    group: '{{ the_user }}'
    mode: 0644

