---
- name: Install base packages (yum)
  become: yes
  ansible.builtin.yum:
    name:
      - vim
      - git
      - curl
      - wget
      - zsh
      - tmux
      - net-tools
      - openssl
    state: latest

- name: "Create user .config directory"
  ansible.builtin.file:
    path: /home/{{ user }}/.config
    state: directory
    mode: 0755
