---
- name: Install base packages (apt)
  become: yes
  ansible.builtin.apt:
    name:
      - vim
      - git
      - curl
      - wget
      - zsh
      - tmux
      - net-tools
      - libssl-dev
    state: latest

- name: "Create user .config directory"
  ansible.builtin.file:
    path: /home/{{ the_user }}/.config
    state: directory
    mode: 0755
