---
- name: Git clone rbenv
  ansible.builtin.git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/{{ user }}/.rbenv
    update: yes

- name: Git clone rbenv build
  ansible.builtin.git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/{{ user }}/.rbenv/plugins/ruby-build
    update: yes

- name: Add line to .zshrc to enable rbenv
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.zshrc
    line: 'eval "$(/home/{{ user }}/.rbenv/bin/rbenv init - zsh)"'
    create: yes
